### ISSUE TITLE
Implement all instructions in emulator

### ISSUE THREAD

**Issue by ed255** [ed255/riscu-jolt#2]
- [ ] lui
- [ ] addi
- [ ] ld
- [ ] sd
- [x] add
- [x] sub
- [x] mul
- [x] divu
- [x] remu
- [x] sltu
- [x] beq @jeong0982 
- [x] jal @jeong0982 
- [x] jalr @jeong0982 
- [ ] ecall

**Comment by jeong0982** [comment]
I'll implement `beq`, `jal`, `jalr` first.
