### ISSUE TITLE
`ark_ff` to `zkcrypto/ff`

### ISSUE THREAD

**Issue by jeong0982** [ed255/riscu-jolt#29]
Since `plonkish` uses `zkcrypto/ff`, there is a compatibility issue if we use lasso within hyperplonk.

**Comment by jeong0982** [comment]
I'll work on this and then try to implement proving by lasso.

**Comment by ed255** [comment]
Sounds good!  I originally chose `ark_ff` because I got the impression that PSE was moving towards the arkworks ecosystem for new research developments, but then I learned that's not the case :P
Hopefully the refactor will not be too painful!
